version: "3"
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
  backend:
    build:
      context: ./djback
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend:
    build:
      context: ./ngfront
    ports:
      - 4200:4200
    depends_on:
      - ./djback
