# Generated by Django 4.0.5 on 2023-01-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Visitor',
        ),
    ]
